version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "deploy-reminder"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ef44d26o6deg"
s3_prefix = "deploy-reminder"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
